// File sinh tự động bởi scripts/scan-heritage-assets.mjs — không sửa tay.
export const HERITAGE_FILES: readonly string[] = [
  "/heritage/brand/logo-seal.svg",
  "/heritage/con-giap/dan.webp",
  "/heritage/con-giap/dau.webp",
  "/heritage/con-giap/hoi.webp",
  "/heritage/con-giap/mao.webp",
  "/heritage/con-giap/mui.webp",
  "/heritage/con-giap/ngo.webp",
  "/heritage/con-giap/suu.webp",
  "/heritage/con-giap/than.webp",
  "/heritage/con-giap/thin.webp",
  "/heritage/con-giap/tuat.webp",
  "/heritage/con-giap/ty-ran.webp",
  "/heritage/con-giap/ty.webp",
  "/heritage/decor/scripture-corner.svg",
  "/heritage/decor/side-left.webp",
  "/heritage/decor/side-right.webp",
  "/heritage/hero/tuoi.webp",
  "/heritage/hero/van-khan.webp",
  "/heritage/van-khan/mung-mot-ngay-ram.webp",
  "/heritage/van-khan/nhom/cau-an.webp",
  "/heritage/van-khan/nhom/di-le.webp",
  "/heritage/van-khan/nhom/le-tet.webp",
  "/heritage/van-khan/nhom/trong-nha.webp",
  "/heritage/van-khan/nhom/viec-lon.webp"
];
