/**
 * Bảng sao tốt / sao xấu suy ngược từ dữ liệu thật.
 *
 * PHƯƠNG PHÁP
 * Lấy danh sách TÊN SAO của 729 ngày dương liên tiếp, ghép với dữ liệu lịch
 * của chính dự án (tháng âm, ngày âm, can/chi ngày, chi tháng theo tiết khí, can
 * năm), rồi thử khớp từng sao với các dạng luật bên dưới. Bảng của mỗi dạng được
 * dựng bằng biểu quyết đa số trên dữ liệu năm 2025, sau đó chấm điểm trên năm
 * 2026 — phần dữ liệu chưa hề dùng để dựng bảng. Một sao chỉ có mặt trong tệp
 * này khi ở bước chấm điểm đạt từ 98% trở lên trên cả ba mặt: đoán đúng
 * tổng thể, bắt đúng những ngày thực sự có sao, và không báo thừa. Các sao còn
 * lại nằm trong danh sách chưa xác định ở sao-report.md.
 *
 * NGUỒN ĐỐI CHIẾU: lichvannien.net (trang riêng cho từng ngày).
 * Chỉ lấy TÊN SAO — không lấy và không lưu bất kỳ câu mô tả nào của trang nguồn.
 * KHOẢNG NGÀY: 01/01/2025 – 31/12/2026.
 * NGÀY THỰC HIỆN: 2026-09-16.
 *
 * Trường `description` để trống có chủ ý — Liêm tự viết.
 */

/** Dạng luật của một sao. Khóa và giá trị đều là chỉ số 0-based, trừ nơi ghi rõ. */
export type SaoRuleKind =
  /** khóa: tháng âm 1–12 — giá trị: chi ngày (Tý = 0) */
  | "lunar-month-chi"
  /** khóa: tháng âm 1–12 — giá trị: can ngày (Giáp = 0) */
  | "lunar-month-can"
  /** khóa: chi tháng tính theo tiết khí (Tý = 0) — giá trị: chi ngày */
  | "term-month-chi"
  /** khóa: can năm — giá trị: can ngày */
  | "year-can-day-can"
  /** khóa: can năm — giá trị: chi ngày */
  | "year-can-day-chi"
  /** khóa: luôn là 0 — giá trị: ngày âm 1–30 */
  | "lunar-day"
  /** khóa: luôn là 0 — giá trị: số dư của số ngày Julius chia cho `period` */
  | "day-cycle"
  /** khóa: chi tháng tính theo tiết khí — giá trị: can ngày */
  | "term-month-can"
  /** khóa: luôn là 0 — giá trị: chỉ số sao nhị thập bát tú của ngày (Giác = 0) */
  | "nhi-thap-bat-tu"
  /**
   * khóa: tháng âm 1–12 — giá trị: can ngày (0–9) hoặc chi ngày cộng 10 (10–21).
   * Tháng vắng mặt trong bảng là tháng ứng vào một hướng bát quái; khi ấy không
   * ngày nào trong tháng có sao.
   */
  | "lunar-month-can-or-chi"
  /** như trên nhưng khóa là chi tháng tính theo tiết khí */
  | "term-month-can-or-chi"
  /** khóa: tháng âm 1–12 — giá trị: ngày âm 1–30 */
  | "lunar-month-lunar-day"
  /** khóa: tháng âm 1–12 — giá trị: số dư của số ngày Julius chia 60 (vòng can chi) */
  | "lunar-month-day-60";

/** Các trường của một ngày mà bảng luật cần đến. */
export interface DerivedSaoDay {
  lunarMonth: number;
  lunarDay: number;
  dayCan: number;
  dayChi: number;
  termMonthChi: number;
  yearCan: number;
  /** Chỉ số sao nhị thập bát tú của ngày, Giác = 0. */
  nhiThapBatTuIndex: number;
  jd: number;
}

/** Bù chỉ số của chi ngày trong dạng luật "tháng âm → can hoặc chi ngày". */
export const CAN_OR_CHI_OFFSET = 10;

export interface DerivedSao {
  name: string;
  isGood: boolean;
  /** Để trống có chủ ý — sẽ do Liêm viết, không chép từ nguồn đối chiếu. */
  description: string;
  kind: SaoRuleKind;
  /** Khóa → danh sách giá trị làm sao ứng vào ngày đó. */
  table: Record<number, number[]>;
  /** Chỉ dùng với kind "day-cycle". */
  period?: number;
  /** Tỷ lệ khớp trên năm 2026, phần dữ liệu không dùng để dựng bảng. */
  matchRate: number;
}

export const DERIVED_SAO: readonly DerivedSao[] = [
  {
    name: "Âm Đức",
    isGood: true,
    description: "Sao phúc ngầm, chủ về việc làm lành không phô trương. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [7],
      3: [5],
      4: [3],
      5: [1],
      6: [11],
      7: [9],
      8: [7],
      9: [5],
      10: [3],
      11: [1],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Bạch hổ",
    isGood: false,
    description: "Sao hắc đạo, chủ về hung hiểm và tang thương. Kiêng cưới hỏi, khai trương, xuất hành, khởi công. Việc an táng thì vẫn tiến hành được.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [8],
      3: [10],
      4: [0],
      5: [2],
      6: [4],
      7: [6],
      8: [8],
      9: [10],
      10: [0],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Băng tiêu ngoạ hãm",
    isGood: false,
    description: "Sao băng tan ngói vỡ, chủ về đổ vỡ. Kiêng mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [1],
      4: [2],
      5: [3],
      6: [10],
      7: [11],
      8: [6],
      9: [7],
      10: [8],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cát Khánh",
    isGood: true,
    description: "Sao tốt lành và mừng vui. Thuận cho mọi việc, nhất là việc hội họp, mừng thọ, khánh thành.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [2],
      3: [11],
      4: [4],
      5: [1],
      6: [6],
      7: [3],
      8: [8],
      9: [5],
      10: [10],
      11: [7],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cẩu Giảo",
    isGood: false,
    description: "Sao chó cắn. Kiêng xuất hành, đi xa.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [6],
      3: [1],
      4: [8],
      5: [3],
      6: [10],
      7: [5],
      8: [0],
      9: [7],
      10: [2],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Câu Trận",
    isGood: false,
    description: "Sao hắc đạo, chủ về vướng mắc dây dưa. Kiêng an táng, ký kết, việc cần dứt điểm gọn gàng.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [1],
      3: [3],
      4: [5],
      5: [7],
      6: [9],
      7: [11],
      8: [1],
      9: [3],
      10: [5],
      11: [7],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Chu tước hắc đạo",
    isGood: false,
    description: "Sao hắc đạo, chủ về thị phi kiện tụng và lời qua tiếng lại. Kiêng về nhà mới, khai trương, hội họp bàn bạc, ký kết.",
    kind: "lunar-month-chi",
    table: {
      1: [3],
      2: [5],
      3: [7],
      4: [9],
      5: [11],
      6: [1],
      7: [3],
      8: [5],
      9: [7],
      10: [9],
      11: [11],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cô thần",
    isGood: false,
    description: "Sao cô độc. Kiêng cưới hỏi, việc cần đông người.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [11],
      3: [0],
      4: [1],
      5: [2],
      6: [3],
      7: [4],
      8: [5],
      9: [6],
      10: [7],
      11: [8],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cửu không",
    isGood: false,
    description: "Sao chín chỗ trống. Kiêng cầu tài, xuất hành, nhập kho.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [1],
      3: [10],
      4: [7],
      5: [3],
      6: [0],
      7: [9],
      8: [6],
      9: [2],
      10: [11],
      11: [8],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Dân nhật, thời đức",
    isGood: true,
    description: "Ngày của dân gặp đức theo mùa, chủ về sự yên ổn hợp thời. Hợp việc thường ngày trong nhà, sửa sang nhỏ, sum họp.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [6],
      3: [6],
      4: [9],
      5: [9],
      6: [9],
      7: [0],
      8: [0],
      9: [0],
      10: [3],
      11: [3],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Dịch Mã",
    isGood: true,
    description: "Sao chủ về di chuyển, đổi dời. Hợp xuất hành, chuyển nhà, đổi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [5],
      3: [2],
      4: [11],
      5: [8],
      6: [5],
      7: [2],
      8: [11],
      9: [8],
      10: [5],
      11: [2],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Đại Hao (Tử Khí, Quan Phú)",
    isGood: false,
    description: "Sao hao tổn lớn, còn gọi Tử khí. Kiêng khai trương, nhập kho, việc tiêu tiền lớn.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [7],
      3: [8],
      4: [9],
      5: [10],
      6: [11],
      7: [0],
      8: [1],
      9: [2],
      10: [3],
      11: [4],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Đại Hồng Sa",
    isGood: true,
    description: "Sao đại cát, chủ về vận may lớn. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [0, 1],
      2: [0, 1],
      3: [0, 1],
      4: [4, 5],
      5: [4, 5],
      6: [4, 5],
      7: [6, 7],
      8: [6, 7],
      9: [6, 7],
      10: [8, 10],
      11: [8, 10],
      12: [8, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa phá",
    isGood: false,
    description: "Sao phá của đất. Kiêng động thổ, xây móng.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [0],
      3: [1],
      4: [2],
      5: [3],
      6: [4],
      7: [5],
      8: [6],
      9: [7],
      10: [8],
      11: [9],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa tài",
    isGood: true,
    description: "Sao tài lộc của đất. Hợp khai trương, buôn bán, ký kết làm ăn.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [7],
      3: [9],
      4: [11],
      5: [1],
      6: [3],
      7: [5],
      8: [7],
      9: [9],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa Tặc",
    isGood: false,
    description: "Sao trộm cướp của đất. Kiêng động thổ, chôn cất, mở kho.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [0],
      3: [11],
      4: [10],
      5: [9],
      6: [8],
      7: [7],
      8: [6],
      9: [5],
      10: [4],
      11: [3],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Độc Hỏa",
    isGood: false,
    description: "Sao lửa độc. Kiêng việc liên quan lửa.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [4],
      3: [3],
      4: [2],
      5: [1],
      6: [0],
      7: [11],
      8: [10],
      9: [9],
      10: [8],
      11: [7],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Giải thần",
    isGood: true,
    description: "Sao hóa giải, làm nhẹ bớt tác động của các sao xấu trong ngày. Hợp cúng tế, cầu an, giải oan, việc kiện tụng.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [8],
      3: [10],
      4: [10],
      5: [0],
      6: [0],
      7: [2],
      8: [2],
      9: [4],
      10: [4],
      11: [6],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hà khôi (Cẩu Giảo)",
    isGood: false,
    description: "Sao xấu, chủ về trở ngại. Kiêng khởi sự, xuất hành.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [6],
      3: [1],
      4: [8],
      5: [3],
      6: [10],
      7: [5],
      8: [0],
      9: [7],
      10: [2],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hỏa tai",
    isGood: false,
    description: "Sao chủ về hỏa hoạn. Kiêng việc liên quan lửa, bếp núc, lợp mái.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [7],
      3: [2],
      4: [8],
      5: [3],
      6: [9],
      7: [4],
      8: [10],
      9: [5],
      10: [11],
      11: [6],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoàng Ân",
    isGood: true,
    description: "Sao ơn trên ban xuống, chủ về được khoan dung che chở. Hợp cầu an, xin xỏ, việc cần người trên chấp thuận.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [1],
      3: [2],
      4: [5],
      5: [9],
      6: [3],
      7: [0],
      8: [6],
      9: [11],
      10: [4],
      11: [8],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoàng Sa",
    isGood: false,
    description: "Sao cát vàng, chủ về che mờ. Kiêng xuất hành, việc cần sáng suốt.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [2],
      3: [0],
      4: [6],
      5: [2],
      6: [0],
      7: [6],
      8: [2],
      9: [0],
      10: [6],
      11: [2],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoang vu",
    isGood: false,
    description: "Sao hoang vắng. Kiêng mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [1, 5, 9],
      2: [1, 5, 9],
      3: [1, 5, 9],
      4: [0, 4, 8],
      5: [0, 4, 8],
      6: [0, 4, 8],
      7: [3, 7, 11],
      8: [3, 7, 11],
      9: [3, 7, 11],
      10: [2, 6, 10],
      11: [2, 6, 10],
      12: [2, 6, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoạt điệu",
    isGood: true,
    description: "Sao chủ về sự linh hoạt và thăng tiến. Hợp việc thăng chức, nhận thưởng, ra mắt, trình báo giấy tờ. Nếu ngày đó gặp sao Thụ tử thì giảm phần tốt.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [10],
      3: [7],
      4: [0],
      5: [9],
      6: [2],
      7: [11],
      8: [4],
      9: [1],
      10: [6],
      11: [3],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Huyền Vũ",
    isGood: false,
    description: "Sao hắc đạo, chủ về trộm cắp và lừa gạt. Kiêng giao dịch, cầu tài, giao tiền, ký kết với người lạ.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [11],
      3: [1],
      4: [3],
      5: [5],
      6: [7],
      7: [9],
      8: [11],
      9: [1],
      10: [3],
      11: [5],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ích Hậu",
    isGood: true,
    description: "Sao thêm phúc về sau. Hợp cưới hỏi, cầu tự, việc tính đường dài.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [6],
      3: [1],
      4: [7],
      5: [2],
      6: [8],
      7: [3],
      8: [9],
      9: [4],
      10: [10],
      11: [5],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Không phòng",
    isGood: false,
    description: "Sao phòng trống. Kiêng cưới hỏi, động phòng.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [0],
      4: [10],
      5: [11],
      6: [7],
      7: [2],
      8: [3],
      9: [6],
      10: [8],
      11: [9],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kiếp sát",
    isGood: false,
    description: "Sao cướp đoạt, chủ về mất mát. Kiêng cầu tài, xuất hành, việc liên quan tiền bạc lớn.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [8],
      3: [5],
      4: [2],
      5: [11],
      6: [8],
      7: [5],
      8: [2],
      9: [11],
      10: [8],
      11: [5],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kim đường",
    isGood: true,
    description: "Sao nhà vàng, chủ về phú quý. Hợp làm nhà, khai trương, việc cầu tài.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [7],
      3: [9],
      4: [11],
      5: [1],
      6: [3],
      7: [5],
      8: [7],
      9: [9],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kính Tâm",
    isGood: true,
    description: "Sao chủ về lòng kính cẩn. Hợp an táng, cải táng, cúng giỗ, tang lễ.",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [1],
      3: [8],
      4: [2],
      5: [9],
      6: [3],
      7: [10],
      8: [4],
      9: [11],
      10: [5],
      11: [0],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lỗ ban sát",
    isGood: false,
    description: "Sao sát của nghề mộc nghề xây. Kiêng dựng cột, cất nóc, đóng giường tủ, khởi công xây cất.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [0],
      3: [0],
      4: [3],
      5: [3],
      6: [3],
      7: [6],
      8: [6],
      9: [6],
      10: [9],
      11: [9],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lộc khố",
    isGood: true,
    description: "Sao kho lộc, chủ về tích trữ của cải. Hợp khai trương, nhập kho, thu tiền, giao dịch.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lôi công",
    isGood: false,
    description: "Sao sấm sét. Kiêng làm nhà, dựng cột, lợp mái.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [11],
      3: [5],
      4: [8],
      5: [2],
      6: [11],
      7: [5],
      8: [8],
      9: [2],
      10: [11],
      11: [5],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lục Bất thành",
    isGood: false,
    description: "Sao sáu việc không thành, chủ về dở dang. Kiêng khởi sự, ký kết, việc cần dứt điểm.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [6],
      3: [10],
      4: [5],
      5: [9],
      6: [1],
      7: [8],
      8: [0],
      9: [4],
      10: [11],
      11: [3],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lục Hợp",
    isGood: true,
    description: "Ngày hợp đôi theo chi, chủ về sự gắn kết. Hợp cưới hỏi, ký kết, giao ước.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [10],
      3: [9],
      4: [8],
      5: [7],
      6: [6],
      7: [5],
      8: [4],
      9: [3],
      10: [2],
      11: [1],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ly sàng",
    isGood: false,
    description: "Sao lìa giường. Kiêng cưới hỏi, kê giường, việc vợ chồng.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [9],
      3: [9],
      4: [2, 6],
      5: [2, 6],
      6: [2, 6],
      7: [10],
      8: [10],
      9: [10],
      10: [5],
      11: [5],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Mãn đức tinh",
    isGood: true,
    description: "Sao đức đầy, chủ về sự viên mãn. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [7],
      3: [4],
      4: [9],
      5: [6],
      6: [11],
      7: [8],
      8: [1],
      9: [10],
      10: [3],
      11: [0],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Mẫu Thương",
    isGood: true,
    description: "Sao kho lẫm, chủ về lương thực của cải. Hợp nhập kho, tích trữ, mua vào.",
    kind: "lunar-month-chi",
    table: {
      1: [0, 11],
      2: [0, 11],
      3: [0, 11],
      4: [2, 3],
      5: [2, 3],
      6: [2, 3],
      7: [1, 4],
      8: [1, 4],
      9: [1, 4],
      10: [8, 9],
      11: [8, 9],
      12: [8, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Minh đường",
    isGood: true,
    description: "Sao hoàng đạo, chủ về chính đại quang minh. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [3],
      3: [5],
      4: [7],
      5: [9],
      6: [11],
      7: [1],
      8: [3],
      9: [5],
      10: [7],
      11: [9],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Minh tinh",
    isGood: true,
    description: "Sao sáng, chủ về sự rõ ràng minh bạch. Tốt cho mọi việc, nhất là việc cần phân xử rành mạch.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [10],
      3: [0],
      4: [2],
      5: [4],
      6: [6],
      7: [8],
      8: [10],
      9: [0],
      10: [2],
      11: [4],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngọc đường",
    isGood: true,
    description: "Sao hoàng đạo, chủ về quý hiển. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [9],
      3: [11],
      4: [1],
      5: [3],
      6: [5],
      7: [7],
      8: [9],
      9: [11],
      10: [1],
      11: [3],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ Hợp",
    isGood: true,
    description: "Sao năm điều hòa hợp, chủ về thuận thảo. Hợp cưới hỏi, kết giao, hợp tác làm ăn.",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [5, 6, 8, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ hư",
    isGood: false,
    description: "Sao năm điều trống. Kiêng cầu tài, nhập kho, khởi sự.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [9],
      3: [1],
      4: [8],
      5: [0],
      6: [4],
      7: [11],
      8: [3],
      9: [7],
      10: [2],
      11: [6],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ phú",
    isGood: true,
    description: "Sao năm điều phúc, chủ về khởi đầu thịnh vượng. Hợp bắt đầu việc mới, động thổ, mở mang làm ăn.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [2],
      3: [5],
      4: [8],
      5: [11],
      6: [2],
      7: [5],
      8: [8],
      9: [11],
      10: [2],
      11: [5],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ Quỹ",
    isGood: false,
    description: "Sao năm quỷ, chủ về thị phi rắc rối. Kiêng xuất hành, việc cần yên ổn.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [2],
      3: [4],
      4: [9],
      5: [3],
      6: [8],
      7: [1],
      8: [5],
      9: [0],
      10: [11],
      11: [7],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Ân",
    isGood: true,
    description: "Sao ân huệ của tháng, chủ về được che chở. Tốt cho mọi việc.",
    kind: "lunar-month-can",
    table: {
      1: [2],
      2: [3],
      3: [6],
      4: [5],
      5: [4],
      6: [7],
      7: [8],
      8: [9],
      9: [6],
      10: [1],
      11: [0],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Đức",
    isGood: true,
    description: "Sao đức của tháng, chủ về sự hanh thông. Ngày có sao này làm việc gì cũng thuận, ít gặp trắc trở.",
    kind: "lunar-month-can",
    table: {
      1: [2],
      2: [0],
      3: [8],
      4: [6],
      5: [2],
      6: [0],
      7: [8],
      8: [6],
      9: [2],
      10: [0],
      11: [8],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt đức hợp",
    isGood: true,
    description: "Sao phối với Nguyệt đức, cùng mang khí lành. Tốt cho cưới hỏi, khai trương, làm nhà, xuất hành. Không nên dùng cho việc kiện tụng.",
    kind: "lunar-month-can",
    table: {
      1: [7],
      2: [5],
      3: [3],
      4: [1],
      5: [7],
      6: [5],
      7: [3],
      8: [1],
      9: [7],
      10: [5],
      11: [3],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt giải",
    isGood: true,
    description: "Sao hóa giải của tháng, làm nhẹ điều xấu. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [8],
      3: [9],
      4: [9],
      5: [10],
      6: [10],
      7: [11],
      8: [11],
      9: [6],
      10: [6],
      11: [7],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hình",
    isGood: false,
    description: "Sao hình phạt của tháng. Kiêng kiện tụng, tranh chấp.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [4],
      4: [8],
      5: [6],
      6: [1],
      7: [2],
      8: [9],
      9: [7],
      10: [11],
      11: [3],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hỏa",
    isGood: false,
    description: "Sao lửa của tháng. Kiêng lợp mái, xây bếp, sửa nhà.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [4],
      3: [3],
      4: [2],
      5: [1],
      6: [0],
      7: [11],
      8: [10],
      9: [9],
      10: [8],
      11: [7],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hư (Nguyệt Sát)",
    isGood: false,
    description: "Sao trống rỗng của tháng. Kiêng cầu tài, nhập kho.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [10],
      3: [7],
      4: [4],
      5: [1],
      6: [10],
      7: [7],
      8: [4],
      9: [1],
      10: [10],
      11: [7],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Không",
    isGood: true,
    description: "Sao chủ về sự trống trải theo nghĩa lành, dọn chỗ cho cái mới. Hợp làm nhà, kê giường, sửa sang chỗ ở, trình đơn từ.",
    kind: "lunar-month-can",
    table: {
      1: [8],
      2: [6],
      3: [2],
      4: [0],
      5: [8],
      6: [6],
      7: [2],
      8: [0],
      9: [8],
      10: [6],
      11: [2],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Kiến chuyển sát",
    isGood: false,
    description: "Sao sát chuyển theo tháng, chủ về xáo trộn. Kiêng động thổ, chuyển nhà, thay đổi lớn.",
    kind: "lunar-month-chi",
    table: {
      1: [3],
      2: [3],
      3: [3],
      4: [6],
      5: [6],
      6: [6],
      7: [9],
      8: [9],
      9: [9],
      10: [0],
      11: [0],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt phá",
    isGood: false,
    description: "Sao phá của tháng. Kiêng làm nhà, khởi công, việc cần bền vững.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [9, 10],
      3: [10],
      4: [11],
      5: [0, 1],
      6: [1],
      7: [2],
      8: [3, 4],
      9: [4],
      10: [5],
      11: [6, 7],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Tài",
    isGood: true,
    description: "Sao tài lộc của tháng. Thuận cho khai trương, cầu tài, xuất hành và giao dịch buôn bán.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [5],
      3: [5],
      4: [7],
      5: [9],
      6: [11],
      7: [6],
      8: [5],
      9: [5],
      10: [7],
      11: [9],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Yếm đại họa",
    isGood: false,
    description: "Sao chán ghét của tháng kèm họa lớn. Kiêng cưới hỏi, xuất hành, mọi việc trọng đại.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [9],
      3: [8],
      4: [7],
      5: [6],
      6: [5],
      7: [4],
      8: [3],
      9: [2],
      10: [1],
      11: [0],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nhân Cách",
    isGood: false,
    description: "Sao cách trở người với người, chủ về ly tán. Kiêng cưới hỏi, hợp tác, hòa giải.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [7],
      3: [5],
      4: [3],
      5: [1],
      6: [11],
      7: [9],
      8: [7],
      9: [5],
      10: [3],
      11: [1],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phi Ma sát (Tai sát)",
    isGood: false,
    description: "Sao xấu, chủ về tan tác. Kiêng cưới hỏi, hợp tác.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [9],
      3: [6],
      4: [3],
      5: [0],
      6: [9],
      7: [6],
      8: [3],
      9: [0],
      10: [9],
      11: [6],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phổ hộ (Hội hộ)",
    isGood: true,
    description: "Sao che chở rộng khắp. Hợp cưới hỏi và xuất hành.",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [2],
      3: [9],
      4: [3],
      5: [10],
      6: [4],
      7: [11],
      8: [5],
      9: [0],
      10: [6],
      11: [1],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phủ đầu dát",
    isGood: false,
    description: "Sao búa bổ đầu, chủ về tai nạn bất ngờ. Kiêng chặt cây, phá dỡ, việc dùng dao búa.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [4],
      3: [4],
      4: [7],
      5: [7],
      6: [7],
      7: [9],
      8: [9],
      9: [9],
      10: [0],
      11: [0],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phúc hậu",
    isGood: true,
    description: "Sao phúc dày. Hợp cầu tài, cầu lộc, việc lâu dài.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [2],
      3: [2],
      4: [5],
      5: [5],
      6: [5],
      7: [8],
      8: [8],
      9: [8],
      10: [11],
      11: [11],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phúc Sinh",
    isGood: true,
    description: "Sao sinh phúc, chủ về điều lành nảy nở. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [3],
      3: [10],
      4: [4],
      5: [11],
      6: [5],
      7: [0],
      8: [6],
      9: [1],
      10: [7],
      11: [2],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quả tú",
    isGood: false,
    description: "Sao lẻ loi. Kiêng cưới hỏi, việc đôi lứa.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quan nhật",
    isGood: true,
    description: "Ngày của quan, chủ về công việc chính sự. Hợp trình báo, làm giấy tờ.",
    kind: "lunar-month-chi",
    table: {
      2: [3],
      5: [6],
      8: [9],
      11: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quỷ khốc",
    isGood: false,
    description: "Sao quỷ khóc, chủ về buồn thương. Kiêng cúng tế, an táng, việc hiếu.",
    kind: "day-cycle",
    period: 12,
    table: {
      0: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Sát chủ",
    isGood: false,
    description: "Sao rất xấu, kiêng mọi việc trọng đại. Đặc biệt kiêng làm nhà, cưới hỏi, an táng.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [7],
      4: [3],
      5: [8],
      6: [10],
      7: [1],
      8: [11],
      9: [6],
      10: [9],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Sinh khí",
    isGood: true,
    description: "Sao khí sinh sôi. Hợp trồng cấy, làm nhà, khởi công, sinh con.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [1],
      3: [2],
      4: [3],
      5: [4],
      6: [5],
      7: [6],
      8: [7],
      9: [8],
      10: [9],
      11: [10],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tam Hợp",
    isGood: true,
    description: "Ngày hợp với ba chi cùng nhóm, chủ về sự hòa thuận. Tốt cho mọi việc, nhất là việc chung với nhiều người.",
    kind: "lunar-month-chi",
    table: {
      1: [6, 10],
      2: [7, 11],
      3: [0, 8],
      4: [1, 9],
      5: [2, 10],
      6: [3, 11],
      7: [0, 4],
      8: [1, 5],
      9: [2, 6],
      10: [3, 7],
      11: [4, 8],
      12: [5, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tam tang",
    isGood: false,
    description: "Sao ba tang, chủ về tang nối tang. Kiêng an táng, cải táng, việc hiếu.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [4],
      3: [4],
      4: [7],
      5: [7],
      6: [7],
      7: [10],
      8: [10],
      9: [10],
      10: [1],
      11: [1],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thanh Long",
    isGood: true,
    description: "Sao hoàng đạo đứng đầu, chủ về cát khí. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [2],
      3: [4],
      4: [6],
      5: [8],
      6: [10],
      7: [0],
      8: [2],
      9: [4],
      10: [6],
      11: [8],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thánh tâm",
    isGood: true,
    description: "Sao chủ về lòng thành. Hợp cúng tế, cầu phúc, lễ bái, việc hiếu nghĩa.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [5],
      3: [0],
      4: [6],
      5: [1],
      6: [7],
      7: [2],
      8: [8],
      9: [3],
      10: [9],
      11: [4],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thần cách",
    isGood: false,
    description: "Sao cách trở thần linh. Kiêng cúng tế, lễ bái.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [3],
      3: [1],
      4: [11],
      5: [9],
      6: [7],
      7: [5],
      8: [3],
      9: [1],
      10: [11],
      11: [9],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Ân",
    isGood: true,
    description: "Sao ơn trời. Tốt cho mọi việc.",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [0, 11, 12, 13, 14, 15, 19, 26, 27, 28, 29, 30, 57, 58],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Cương (hay Diệt Môn)",
    isGood: false,
    description: "Sao xấu lớn, còn gọi Diệt môn. Kiêng mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [7],
      4: [2],
      5: [9],
      6: [4],
      7: [11],
      8: [6],
      9: [1],
      10: [8],
      11: [3],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Hỏa",
    isGood: false,
    description: "Sao lửa trời. Kiêng lợp mái, xây bếp, đốt lửa.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [3],
      3: [6],
      4: [9],
      5: [0],
      6: [3],
      7: [6],
      8: [9],
      9: [0],
      10: [3],
      11: [6],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên hỷ",
    isGood: true,
    description: "Sao mừng vui, chủ về hỷ sự. Rất hợp cưới hỏi, ăn hỏi, dạm ngõ và các việc vui trong nhà.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [11],
      3: [0],
      4: [1],
      5: [2],
      6: [3],
      7: [4],
      8: [5],
      9: [6],
      10: [7],
      11: [8],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Lại",
    isGood: false,
    description: "Sao ngục lại. Kiêng kiện tụng, việc dính dáng pháp luật.",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [6],
      3: [3],
      4: [0],
      5: [9],
      6: [6],
      7: [3],
      8: [0],
      9: [9],
      10: [6],
      11: [3],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Mã (Lộc mã)",
    isGood: true,
    description: "Sao ngựa trời, chủ về đi lại. Hợp xuất hành, chuyển nhà, đi xa, mở đường làm ăn.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [8],
      3: [10],
      4: [0],
      5: [2],
      6: [4],
      7: [6],
      8: [8],
      9: [10],
      10: [0],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Ngục",
    isGood: false,
    description: "Sao ngục trời, chủ về giam hãm vướng mắc. Kiêng kiện tụng, việc dính dáng pháp luật.",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [3],
      3: [6],
      4: [9],
      5: [0],
      6: [3],
      7: [6],
      8: [9],
      9: [0],
      10: [3],
      11: [6],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên ôn",
    isGood: false,
    description: "Sao ôn dịch của trời. Kiêng làm nhà, dựng cột.",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [10],
      3: [4],
      4: [2],
      5: [6],
      6: [0],
      7: [9],
      8: [8],
      9: [5],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên phú",
    isGood: true,
    description: "Sao chủ về sự sung túc đầy đặn. Hợp làm nhà, xây cất, khai trương, và việc an táng.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Phúc",
    isGood: true,
    description: "Sao phúc của trời. Tốt cho mọi việc, nhất là cầu an, lễ bái.",
    kind: "lunar-month-can",
    table: {
      1: [5],
      2: [4],
      4: [7, 9],
      5: [6, 8],
      7: [1],
      8: [0],
      10: [3],
      11: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Quan",
    isGood: true,
    description: "Sao chủ về chức vị, công danh. Hợp việc nhậm chức, trình đơn từ, giao thiệp với cơ quan.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [0],
      3: [2],
      4: [4],
      5: [6],
      6: [8],
      7: [10],
      8: [0],
      9: [2],
      10: [4],
      11: [6],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Quý",
    isGood: true,
    description: "Sao quý nhân, chủ về gặp người giúp đỡ. Thuận cho mọi việc, nhất là việc cần nhờ cậy người khác.",
    kind: "lunar-month-can",
    table: {
      1: [0, 1],
      2: [0, 1],
      3: [0, 1],
      4: [2, 3],
      5: [2, 3],
      6: [2, 3],
      7: [6, 7],
      8: [6, 7],
      9: [6, 7],
      10: [8, 9],
      11: [8, 9],
      12: [8, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên tài",
    isGood: true,
    description: "Sao tài lộc của trời. Hợp khai trương, cầu tài, mở hàng đầu năm.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [6],
      3: [8],
      4: [10],
      5: [0],
      6: [2],
      7: [4],
      8: [6],
      9: [8],
      10: [10],
      11: [0],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên tặc",
    isGood: false,
    description: "Sao trộm cướp của trời. Kiêng cầu tài, mở kho, khai trương.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [9],
      3: [2],
      4: [7],
      5: [0],
      6: [5],
      7: [10],
      8: [3],
      9: [8],
      10: [1],
      11: [6],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên thành",
    isGood: true,
    description: "Sao chủ về sự thành tựu. Tốt cho việc hoàn tất, nghiệm thu, bàn giao.",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [9],
      3: [11],
      4: [1],
      5: [3],
      6: [5],
      7: [7],
      8: [9],
      9: [11],
      10: [1],
      11: [3],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Thụy",
    isGood: true,
    description: "Sao điềm lành của trời, chủ về tin vui bất ngờ. Tốt cho mọi việc, nhất là việc chờ kết quả.",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [25, 26, 28, 37, 59],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ cẩm",
    isGood: false,
    description: "Sao cấm đất. Kiêng xây cất, an táng.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [11],
      3: [11],
      4: [2],
      5: [2],
      6: [2],
      7: [5],
      8: [5],
      9: [5],
      10: [8],
      11: [8],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ ôn (Thiên cẩu)",
    isGood: false,
    description: "Sao ôn dịch của đất. Kiêng động thổ, làm chuồng trại.",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ phủ",
    isGood: false,
    description: "Sao phủ đất. Kiêng động thổ, xây cất.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [3],
      3: [4],
      4: [5],
      5: [6],
      6: [7],
      7: [8],
      8: [9],
      9: [10],
      10: [11],
      11: [0],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thụ tử",
    isGood: false,
    description: "Sao chủ về chết chóc, cùng tính với Thọ tử. Kiêng cưới hỏi, khai trương, làm nhà, mọi việc trọng đại. Việc săn bắt thì không kỵ.",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [4],
      3: [11],
      4: [5],
      5: [0],
      6: [6],
      7: [1],
      8: [7],
      9: [2],
      10: [8],
      11: [3],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tiểu Hao",
    isGood: false,
    description: "Sao hao mòn. Kiêng cầu tài, nhập kho.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [6],
      3: [7],
      4: [8],
      5: [9],
      6: [10],
      7: [11],
      8: [0],
      9: [1],
      10: [2],
      11: [3],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tiểu Hồng Sa",
    isGood: false,
    description: "Sao may nhỏ, cùng tính với Đại hồng sa nhưng nhẹ hơn. Tốt cho việc vừa và nhỏ.",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [9],
      3: [1],
      4: [5],
      5: [9],
      6: [1],
      7: [5],
      8: [9],
      9: [1],
      10: [5],
      11: [9],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tội chỉ",
    isGood: false,
    description: "Sao tội lỗi tìm đến. Kiêng kiện tụng, việc khuất tất.",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [0],
      3: [7],
      4: [1],
      5: [8],
      6: [2],
      7: [9],
      8: [3],
      9: [10],
      10: [4],
      11: [11],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Trùng phục",
    isGood: false,
    description: "Sao chủ về điều xấu lặp lại. Kiêng an táng, việc hiếu.",
    kind: "lunar-month-can",
    table: {
      1: [6],
      2: [7],
      3: [5],
      4: [8],
      5: [9],
      6: [4],
      7: [0],
      8: [1],
      9: [5],
      10: [8],
      11: [9],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Trùng Tang",
    isGood: false,
    description: "Sao chủ về tang nối tang. Kiêng an táng, cải táng, việc hiếu.",
    kind: "lunar-month-can",
    table: {
      1: [0],
      2: [1],
      3: [5],
      4: [2],
      5: [3],
      6: [5],
      7: [6],
      8: [7],
      9: [5],
      10: [8],
      11: [9],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tục Thế",
    isGood: true,
    description: "Sao nối tiếp, chủ về sự kế thừa. Hợp cưới hỏi, cầu tự, việc gia đình.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [7],
      3: [2],
      4: [8],
      5: [3],
      6: [9],
      7: [4],
      8: [10],
      9: [5],
      10: [11],
      11: [6],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tuế hợp",
    isGood: true,
    description: "Sao hợp với năm, chủ về thuận theo vận năm. Tốt cho mọi việc trong năm đó.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [0],
      3: [11],
      4: [10],
      5: [9],
      6: [8],
      7: [7],
      8: [6],
      9: [5],
      10: [4],
      11: [3],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tứ thời cô quả",
    isGood: false,
    description: "Sao cô quả bốn mùa, chủ về lẻ loi. Kiêng cưới hỏi, việc đôi lứa, việc cần đông người.",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [1],
      3: [1],
      4: [4],
      5: [4],
      6: [4],
      7: [7],
      8: [7],
      9: [7],
      10: [10],
      11: [10],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "U Vi tinh",
    isGood: true,
    description: "Sao lành kín đáo, chủ về sự thuận lợi âm thầm. Tốt cho mọi việc.",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [4],
      3: [1],
      4: [6],
      5: [3],
      6: [8],
      7: [5],
      8: [10],
      9: [7],
      10: [0],
      11: [9],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Vãng vong (Thổ kỵ)",
    isGood: false,
    description: "Sao chủ về đi mà không về. Kiêng xuất hành, cưới hỏi, cầu tài.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [5],
      3: [8],
      4: [11],
      5: [3],
      6: [6],
      7: [9],
      8: [0],
      9: [4],
      10: [7],
      11: [10],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Yếu yên (thiên quý)",
    isGood: true,
    description: "Sao yên ổn đi cùng quý nhân. Hợp dọn nhà, an vị bàn thờ, việc cần sự êm ấm lâu dài.",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [8],
      3: [3],
      4: [9],
      5: [4],
      6: [10],
      7: [5],
      8: [11],
      9: [6],
      10: [0],
      11: [7],
      12: [1],
    },
    matchRate: 1.0000,
  },
];

/** Khóa tra bảng của một ngày theo dạng luật đã cho. */
function ruleKey(sao: DerivedSao, day: DerivedSaoDay): number {
  switch (sao.kind) {
    case "lunar-month-chi":
    case "lunar-month-can":
    case "lunar-month-can-or-chi":
    case "lunar-month-lunar-day":
    case "lunar-month-day-60":
      return day.lunarMonth;
    case "term-month-chi":
    case "term-month-can":
    case "term-month-can-or-chi":
      return day.termMonthChi;
    case "year-can-day-can":
    case "year-can-day-chi":
      return day.yearCan;
    case "lunar-day":
    case "day-cycle":
    case "nhi-thap-bat-tu":
      return 0;
  }
}

/** Các giá trị mà một ngày có thể ứng vào theo dạng luật đã cho. */
function ruleValues(sao: DerivedSao, day: DerivedSaoDay): number[] {
  switch (sao.kind) {
    case "lunar-month-chi":
    case "term-month-chi":
    case "year-can-day-chi":
      return [day.dayChi];
    case "lunar-month-can":
    case "term-month-can":
    case "year-can-day-can":
      return [day.dayCan];
    case "lunar-day":
    case "lunar-month-lunar-day":
      return [day.lunarDay];
    case "day-cycle":
      return [day.jd % (sao.period ?? 1)];
    case "lunar-month-day-60":
      return [day.jd % 60];
    case "nhi-thap-bat-tu":
      return [day.nhiThapBatTuIndex];
    case "lunar-month-can-or-chi":
    case "term-month-can-or-chi":
      return [day.dayCan, day.dayChi + CAN_OR_CHI_OFFSET];
  }
}

/** Ngày đã cho có ứng sao `sao` hay không. */
export function derivedSaoMatches(sao: DerivedSao, day: DerivedSaoDay): boolean {
  const values = sao.table[ruleKey(sao, day)];
  if (values === undefined) return false;
  return ruleValues(sao, day).some((v) => values.includes(v));
}
