/**
 * Bảng sao tốt / sao xấu suy ngược từ dữ liệu thật.
 *
 * PHƯƠNG PHÁP
 * Lấy danh sách TÊN SAO của 729 ngày dương liên tiếp, ghép với dữ liệu lịch
 * của chính dự án (tháng âm, ngày âm, can/chi ngày, chi tháng theo tiết khí, can
 * năm), rồi thử khớp từng sao với các dạng luật bên dưới. Bảng của mỗi dạng được
 * dựng bằng biểu quyết đa số trên dữ liệu năm 2025, sau đó chấm điểm trên năm
 * 2026 — phần dữ liệu chưa hề dùng để dựng bảng. Một sao chỉ có mặt trong tệp
 * này khi ở bước chấm điểm đạt từ 98% trở lên trên cả ba mặt: đoán đúng
 * tổng thể, bắt đúng những ngày thực sự có sao, và không báo thừa. Các sao còn
 * lại nằm trong danh sách chưa xác định ở sao-report.md.
 *
 * NGUỒN ĐỐI CHIẾU: lichvannien.net (trang riêng cho từng ngày).
 * Chỉ lấy TÊN SAO — không lấy và không lưu bất kỳ câu mô tả nào của trang nguồn.
 * KHOẢNG NGÀY: 01/01/2025 – 31/12/2026.
 * NGÀY THỰC HIỆN: 2026-09-16.
 *
 * Trường `description` để trống có chủ ý — Liêm tự viết.
 * Tệp này CHƯA được nối vào getDayInfo().
 */

/** Dạng luật của một sao. Khóa và giá trị đều là chỉ số 0-based, trừ nơi ghi rõ. */
export type SaoRuleKind =
  /** khóa: tháng âm 1–12 — giá trị: chi ngày (Tý = 0) */
  | "lunar-month-chi"
  /** khóa: tháng âm 1–12 — giá trị: can ngày (Giáp = 0) */
  | "lunar-month-can"
  /** khóa: chi tháng tính theo tiết khí (Tý = 0) — giá trị: chi ngày */
  | "term-month-chi"
  /** khóa: can năm — giá trị: can ngày */
  | "year-can-day-can"
  /** khóa: can năm — giá trị: chi ngày */
  | "year-can-day-chi"
  /** khóa: luôn là 0 — giá trị: ngày âm 1–30 */
  | "lunar-day"
  /** khóa: luôn là 0 — giá trị: số dư của số ngày Julius chia cho `period` */
  | "day-cycle";

/** Các trường của một ngày mà bảng luật cần đến. */
export interface DerivedSaoDay {
  lunarMonth: number;
  lunarDay: number;
  dayCan: number;
  dayChi: number;
  termMonthChi: number;
  yearCan: number;
  jd: number;
}

export interface DerivedSao {
  name: string;
  isGood: boolean;
  /** Để trống có chủ ý — sẽ do Liêm viết, không chép từ nguồn đối chiếu. */
  description: string;
  kind: SaoRuleKind;
  /** Khóa → danh sách giá trị làm sao ứng vào ngày đó. */
  table: Record<number, number[]>;
  /** Chỉ dùng với kind "day-cycle". */
  period?: number;
  /** Tỷ lệ khớp trên năm 2026, phần dữ liệu không dùng để dựng bảng. */
  matchRate: number;
}

export const DERIVED_SAO: readonly DerivedSao[] = [
  {
    name: "Âm Đức",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [7],
      3: [5],
      4: [3],
      5: [1],
      6: [11],
      7: [9],
      8: [7],
      9: [5],
      10: [3],
      11: [1],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Bạch hổ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [8],
      3: [10],
      4: [0],
      5: [2],
      6: [4],
      7: [6],
      8: [8],
      9: [10],
      10: [0],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Băng tiêu ngoạ hãm",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [1],
      4: [2],
      5: [3],
      6: [10],
      7: [11],
      8: [6],
      9: [7],
      10: [8],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cát Khánh",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [2],
      3: [11],
      4: [4],
      5: [1],
      6: [6],
      7: [3],
      8: [8],
      9: [5],
      10: [10],
      11: [7],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cẩu Giảo",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [6],
      3: [1],
      4: [8],
      5: [3],
      6: [10],
      7: [5],
      8: [0],
      9: [7],
      10: [2],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Câu Trận",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [1],
      3: [3],
      4: [5],
      5: [7],
      6: [9],
      7: [11],
      8: [1],
      9: [3],
      10: [5],
      11: [7],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Chu tước hắc đạo",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [3],
      2: [5],
      3: [7],
      4: [9],
      5: [11],
      6: [1],
      7: [3],
      8: [5],
      9: [7],
      10: [9],
      11: [11],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cô thần",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [11],
      3: [0],
      4: [1],
      5: [2],
      6: [3],
      7: [4],
      8: [5],
      9: [6],
      10: [7],
      11: [8],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Cửu không",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [1],
      3: [10],
      4: [7],
      5: [3],
      6: [0],
      7: [9],
      8: [6],
      9: [2],
      10: [11],
      11: [8],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Dân nhật, thời đức",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [6],
      3: [6],
      4: [9],
      5: [9],
      6: [9],
      7: [0],
      8: [0],
      9: [0],
      10: [3],
      11: [3],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Dịch Mã",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [5],
      3: [2],
      4: [11],
      5: [8],
      6: [5],
      7: [2],
      8: [11],
      9: [8],
      10: [5],
      11: [2],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Đại Hao (Tử Khí, Quan Phú)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [7],
      3: [8],
      4: [9],
      5: [10],
      6: [11],
      7: [0],
      8: [1],
      9: [2],
      10: [3],
      11: [4],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Đại Hồng Sa",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0, 1],
      2: [0, 1],
      3: [0, 1],
      4: [4, 5],
      5: [4, 5],
      6: [4, 5],
      7: [6, 7],
      8: [6, 7],
      9: [6, 7],
      10: [8, 10],
      11: [8, 10],
      12: [8, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa phá",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [0],
      3: [1],
      4: [2],
      5: [3],
      6: [4],
      7: [5],
      8: [6],
      9: [7],
      10: [8],
      11: [9],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa tài",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [7],
      3: [9],
      4: [11],
      5: [1],
      6: [3],
      7: [5],
      8: [7],
      9: [9],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Địa Tặc",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [0],
      3: [11],
      4: [10],
      5: [9],
      6: [8],
      7: [7],
      8: [6],
      9: [5],
      10: [4],
      11: [3],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Độc Hỏa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [4],
      3: [3],
      4: [2],
      5: [1],
      6: [0],
      7: [11],
      8: [10],
      9: [9],
      10: [8],
      11: [7],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Giải thần",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [8],
      3: [10],
      4: [10],
      5: [0],
      6: [0],
      7: [2],
      8: [2],
      9: [4],
      10: [4],
      11: [6],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hà khôi(Cẩu Giảo)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [6],
      3: [1],
      4: [8],
      5: [3],
      6: [10],
      7: [5],
      8: [0],
      9: [7],
      10: [2],
      11: [9],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hỏa tai",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [7],
      3: [2],
      4: [8],
      5: [3],
      6: [9],
      7: [4],
      8: [10],
      9: [5],
      10: [11],
      11: [6],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoàng Ân",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [1],
      3: [2],
      4: [5],
      5: [9],
      6: [3],
      7: [0],
      8: [6],
      9: [11],
      10: [4],
      11: [8],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoàng Sa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [2],
      3: [0],
      4: [6],
      5: [2],
      6: [0],
      7: [6],
      8: [2],
      9: [0],
      10: [6],
      11: [2],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoang vu",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1, 5, 9],
      2: [1, 5, 9],
      3: [1, 5, 9],
      4: [0, 4, 8],
      5: [0, 4, 8],
      6: [0, 4, 8],
      7: [3, 7, 11],
      8: [3, 7, 11],
      9: [3, 7, 11],
      10: [2, 6, 10],
      11: [2, 6, 10],
      12: [2, 6, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Hoạt điệu",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [10],
      3: [7],
      4: [0],
      5: [9],
      6: [2],
      7: [11],
      8: [4],
      9: [1],
      10: [6],
      11: [3],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Huyền Vũ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [11],
      3: [1],
      4: [3],
      5: [5],
      6: [7],
      7: [9],
      8: [11],
      9: [1],
      10: [3],
      11: [5],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ích Hậu",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [6],
      3: [1],
      4: [7],
      5: [2],
      6: [8],
      7: [3],
      8: [9],
      9: [4],
      10: [10],
      11: [5],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Không phòng",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [0],
      4: [10],
      5: [11],
      6: [7],
      7: [2],
      8: [3],
      9: [6],
      10: [8],
      11: [9],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kiếp sát",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [8],
      3: [5],
      4: [2],
      5: [11],
      6: [8],
      7: [5],
      8: [2],
      9: [11],
      10: [8],
      11: [5],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kim đường",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [7],
      3: [9],
      4: [11],
      5: [1],
      6: [3],
      7: [5],
      8: [7],
      9: [9],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Kính Tâm",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [1],
      3: [8],
      4: [2],
      5: [9],
      6: [3],
      7: [10],
      8: [4],
      9: [11],
      10: [5],
      11: [0],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lỗ ban sát",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [0],
      3: [0],
      4: [3],
      5: [3],
      6: [3],
      7: [6],
      8: [6],
      9: [6],
      10: [9],
      11: [9],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lộc khố",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lôi công",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [11],
      3: [5],
      4: [8],
      5: [2],
      6: [11],
      7: [5],
      8: [8],
      9: [2],
      10: [11],
      11: [5],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lục Bất thành",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [6],
      3: [10],
      4: [5],
      5: [9],
      6: [1],
      7: [8],
      8: [0],
      9: [4],
      10: [11],
      11: [3],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Lục Hợp",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [10],
      3: [9],
      4: [8],
      5: [7],
      6: [6],
      7: [5],
      8: [4],
      9: [3],
      10: [2],
      11: [1],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ly sàng",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [9],
      3: [9],
      4: [2, 6],
      5: [2, 6],
      6: [2, 6],
      7: [10],
      8: [10],
      9: [10],
      10: [5],
      11: [5],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Mãn đức tinh",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [7],
      3: [4],
      4: [9],
      5: [6],
      6: [11],
      7: [8],
      8: [1],
      9: [10],
      10: [3],
      11: [0],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Mẫu Thương",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0, 11],
      2: [0, 11],
      3: [0, 11],
      4: [2, 3],
      5: [2, 3],
      6: [2, 3],
      7: [1, 4],
      8: [1, 4],
      9: [1, 4],
      10: [8, 9],
      11: [8, 9],
      12: [8, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Minh đường",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [3],
      3: [5],
      4: [7],
      5: [9],
      6: [11],
      7: [1],
      8: [3],
      9: [5],
      10: [7],
      11: [9],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Minh tinh",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [10],
      3: [0],
      4: [2],
      5: [4],
      6: [6],
      7: [8],
      8: [10],
      9: [0],
      10: [2],
      11: [4],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngọc đường",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [9],
      3: [11],
      4: [1],
      5: [3],
      6: [5],
      7: [7],
      8: [9],
      9: [11],
      10: [1],
      11: [3],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ Hợp",
    isGood: true,
    description: "",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [5, 6, 8, 10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ hư",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [9],
      3: [1],
      4: [8],
      5: [0],
      6: [4],
      7: [11],
      8: [3],
      9: [7],
      10: [2],
      11: [6],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ phú",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [2],
      3: [5],
      4: [8],
      5: [11],
      6: [2],
      7: [5],
      8: [8],
      9: [11],
      10: [2],
      11: [5],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Ngũ Quỹ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [2],
      3: [4],
      4: [9],
      5: [3],
      6: [8],
      7: [1],
      8: [5],
      9: [0],
      10: [11],
      11: [7],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Ân",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [2],
      2: [3],
      3: [6],
      4: [5],
      5: [4],
      6: [7],
      7: [8],
      8: [9],
      9: [6],
      10: [1],
      11: [0],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Đức",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [2],
      2: [0],
      3: [8],
      4: [6],
      5: [2],
      6: [0],
      7: [8],
      8: [6],
      9: [2],
      10: [0],
      11: [8],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt đức hợp",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [7],
      2: [5],
      3: [3],
      4: [1],
      5: [7],
      6: [5],
      7: [3],
      8: [1],
      9: [7],
      10: [5],
      11: [3],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt giải",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [8],
      3: [9],
      4: [9],
      5: [10],
      6: [10],
      7: [11],
      8: [11],
      9: [6],
      10: [6],
      11: [7],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hình",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [4],
      4: [8],
      5: [6],
      6: [1],
      7: [2],
      8: [9],
      9: [7],
      10: [11],
      11: [3],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hỏa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [4],
      3: [3],
      4: [2],
      5: [1],
      6: [0],
      7: [11],
      8: [10],
      9: [9],
      10: [8],
      11: [7],
      12: [6],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Hư (Nguyệt Sát)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [10],
      3: [7],
      4: [4],
      5: [1],
      6: [10],
      7: [7],
      8: [4],
      9: [1],
      10: [10],
      11: [7],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Không",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [8],
      2: [6],
      3: [2],
      4: [0],
      5: [8],
      6: [6],
      7: [2],
      8: [0],
      9: [8],
      10: [6],
      11: [2],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Kiến chuyển sát",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [3],
      2: [3],
      3: [3],
      4: [6],
      5: [6],
      6: [6],
      7: [9],
      8: [9],
      9: [9],
      10: [0],
      11: [0],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt phá",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [9, 10],
      3: [10],
      4: [11],
      5: [0, 1],
      6: [1],
      7: [2],
      8: [3, 4],
      9: [4],
      10: [5],
      11: [6, 7],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Tài",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [5],
      3: [5],
      4: [7],
      5: [9],
      6: [11],
      7: [6],
      8: [5],
      9: [5],
      10: [7],
      11: [9],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nguyệt Yếm đại họa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [9],
      3: [8],
      4: [7],
      5: [6],
      6: [5],
      7: [4],
      8: [3],
      9: [2],
      10: [1],
      11: [0],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Nhân Cách",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [7],
      3: [5],
      4: [3],
      5: [1],
      6: [11],
      7: [9],
      8: [7],
      9: [5],
      10: [3],
      11: [1],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phi Ma sát (Tai sát)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [9],
      3: [6],
      4: [3],
      5: [0],
      6: [9],
      7: [6],
      8: [3],
      9: [0],
      10: [9],
      11: [6],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phổ hộ (Hội hộ)",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [8],
      2: [2],
      3: [9],
      4: [3],
      5: [10],
      6: [4],
      7: [11],
      8: [5],
      9: [0],
      10: [6],
      11: [1],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phủ đầu dát",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [4],
      3: [4],
      4: [7],
      5: [7],
      6: [7],
      7: [9],
      8: [9],
      9: [9],
      10: [0],
      11: [0],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phúc hậu",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [2],
      3: [2],
      4: [5],
      5: [5],
      6: [5],
      7: [8],
      8: [8],
      9: [8],
      10: [11],
      11: [11],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Phúc Sinh",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [3],
      3: [10],
      4: [4],
      5: [11],
      6: [5],
      7: [0],
      8: [6],
      9: [1],
      10: [7],
      11: [2],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quả tú",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quan nhật",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      2: [3],
      5: [6],
      8: [9],
      11: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Quỷ khốc",
    isGood: false,
    description: "",
    kind: "day-cycle",
    period: 12,
    table: {
      0: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Sát chủ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [7],
      4: [3],
      5: [8],
      6: [10],
      7: [1],
      8: [11],
      9: [6],
      10: [9],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Sinh khí",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [1],
      3: [2],
      4: [3],
      5: [4],
      6: [5],
      7: [6],
      8: [7],
      9: [8],
      10: [9],
      11: [10],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tam Hợp",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6, 10],
      2: [7, 11],
      3: [0, 8],
      4: [1, 9],
      5: [2, 10],
      6: [3, 11],
      7: [0, 4],
      8: [1, 5],
      9: [2, 6],
      10: [3, 7],
      11: [4, 8],
      12: [5, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tam tang",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [4],
      3: [4],
      4: [7],
      5: [7],
      6: [7],
      7: [10],
      8: [10],
      9: [10],
      10: [1],
      11: [1],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thanh Long",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [2],
      3: [4],
      4: [6],
      5: [8],
      6: [10],
      7: [0],
      8: [2],
      9: [4],
      10: [6],
      11: [8],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thánh tâm",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [5],
      3: [0],
      4: [6],
      5: [1],
      6: [7],
      7: [2],
      8: [8],
      9: [3],
      10: [9],
      11: [4],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thần cách",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [3],
      3: [1],
      4: [11],
      5: [9],
      6: [7],
      7: [5],
      8: [3],
      9: [1],
      10: [11],
      11: [9],
      12: [7],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Ân",
    isGood: true,
    description: "",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [0, 11, 12, 13, 14, 15, 19, 26, 27, 28, 29, 30, 57, 58],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Cương (hay Diệt Môn)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [0],
      3: [7],
      4: [2],
      5: [9],
      6: [4],
      7: [11],
      8: [6],
      9: [1],
      10: [8],
      11: [3],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Hỏa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [3],
      3: [6],
      4: [9],
      5: [0],
      6: [3],
      7: [6],
      8: [9],
      9: [0],
      10: [3],
      11: [6],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên hỷ",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [11],
      3: [0],
      4: [1],
      5: [2],
      6: [3],
      7: [4],
      8: [5],
      9: [6],
      10: [7],
      11: [8],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Lại",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [9],
      2: [6],
      3: [3],
      4: [0],
      5: [9],
      6: [6],
      7: [3],
      8: [0],
      9: [9],
      10: [6],
      11: [3],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Mã (Lộc mã)",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [8],
      3: [10],
      4: [0],
      5: [2],
      6: [4],
      7: [6],
      8: [8],
      9: [10],
      10: [0],
      11: [2],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Ngục",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [0],
      2: [3],
      3: [6],
      4: [9],
      5: [0],
      6: [3],
      7: [6],
      8: [9],
      9: [0],
      10: [3],
      11: [6],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên ôn",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [10],
      3: [4],
      4: [2],
      5: [6],
      6: [0],
      7: [9],
      8: [8],
      9: [5],
      10: [11],
      11: [1],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên phú",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Phúc",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [5],
      2: [4],
      4: [7, 9],
      5: [6, 8],
      7: [1],
      8: [0],
      10: [3],
      11: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Quan",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [0],
      3: [2],
      4: [4],
      5: [6],
      6: [8],
      7: [10],
      8: [0],
      9: [2],
      10: [4],
      11: [6],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Quý",
    isGood: true,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [0, 1],
      2: [0, 1],
      3: [0, 1],
      4: [2, 3],
      5: [2, 3],
      6: [2, 3],
      7: [6, 7],
      8: [6, 7],
      9: [6, 7],
      10: [8, 9],
      11: [8, 9],
      12: [8, 9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên tài",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [6],
      3: [8],
      4: [10],
      5: [0],
      6: [2],
      7: [4],
      8: [6],
      9: [8],
      10: [10],
      11: [0],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên tặc",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [9],
      3: [2],
      4: [7],
      5: [0],
      6: [5],
      7: [10],
      8: [3],
      9: [8],
      10: [1],
      11: [6],
      12: [11],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên thành",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [7],
      2: [9],
      3: [11],
      4: [1],
      5: [3],
      6: [5],
      7: [7],
      8: [9],
      9: [11],
      10: [1],
      11: [3],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thiên Thụy",
    isGood: true,
    description: "",
    kind: "day-cycle",
    period: 60,
    table: {
      0: [25, 26, 28, 37, 59],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ cẩm",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [11],
      3: [11],
      4: [2],
      5: [2],
      6: [2],
      7: [5],
      8: [5],
      9: [5],
      10: [8],
      11: [8],
      12: [8],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ ôn (Thiên cẩu)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [4],
      2: [5],
      3: [6],
      4: [7],
      5: [8],
      6: [9],
      7: [10],
      8: [11],
      9: [0],
      10: [1],
      11: [2],
      12: [3],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thổ phủ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [3],
      3: [4],
      4: [5],
      5: [6],
      6: [7],
      7: [8],
      8: [9],
      9: [10],
      10: [11],
      11: [0],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Thụ tử",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [10],
      2: [4],
      3: [11],
      4: [5],
      5: [0],
      6: [6],
      7: [1],
      8: [7],
      9: [2],
      10: [8],
      11: [3],
      12: [9],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tiểu Hao",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [6],
      3: [7],
      4: [8],
      5: [9],
      6: [10],
      7: [11],
      8: [0],
      9: [1],
      10: [2],
      11: [3],
      12: [4],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tiểu Hồng Sa",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [5],
      2: [9],
      3: [1],
      4: [5],
      5: [9],
      6: [1],
      7: [5],
      8: [9],
      9: [1],
      10: [5],
      11: [9],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tội chỉ",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [6],
      2: [0],
      3: [7],
      4: [1],
      5: [8],
      6: [2],
      7: [9],
      8: [3],
      9: [10],
      10: [4],
      11: [11],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Trùng phục",
    isGood: false,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [6],
      2: [7],
      3: [5],
      4: [8],
      5: [9],
      6: [4],
      7: [0],
      8: [1],
      9: [5],
      10: [8],
      11: [9],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Trùng Tang",
    isGood: false,
    description: "",
    kind: "lunar-month-can",
    table: {
      1: [0],
      2: [1],
      3: [5],
      4: [2],
      5: [3],
      6: [5],
      7: [6],
      8: [7],
      9: [5],
      10: [8],
      11: [9],
      12: [5],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tục Thế",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [7],
      3: [2],
      4: [8],
      5: [3],
      6: [9],
      7: [4],
      8: [10],
      9: [5],
      10: [11],
      11: [6],
      12: [0],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tuế hợp",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [0],
      3: [11],
      4: [10],
      5: [9],
      6: [8],
      7: [7],
      8: [6],
      9: [5],
      10: [4],
      11: [3],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Tứ thời cô quả",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [1],
      2: [1],
      3: [1],
      4: [4],
      5: [4],
      6: [4],
      7: [7],
      8: [7],
      9: [7],
      10: [10],
      11: [10],
      12: [10],
    },
    matchRate: 1.0000,
  },
  {
    name: "U Vi tinh",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [11],
      2: [4],
      3: [1],
      4: [6],
      5: [3],
      6: [8],
      7: [5],
      8: [10],
      9: [7],
      10: [0],
      11: [9],
      12: [2],
    },
    matchRate: 1.0000,
  },
  {
    name: "Vãng vong (Thổ kỵ)",
    isGood: false,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [5],
      3: [8],
      4: [11],
      5: [3],
      6: [6],
      7: [9],
      8: [0],
      9: [4],
      10: [7],
      11: [10],
      12: [1],
    },
    matchRate: 1.0000,
  },
  {
    name: "Yếu yên (thiên quý)",
    isGood: true,
    description: "",
    kind: "lunar-month-chi",
    table: {
      1: [2],
      2: [8],
      3: [3],
      4: [9],
      5: [4],
      6: [10],
      7: [5],
      8: [11],
      9: [6],
      10: [0],
      11: [7],
      12: [1],
    },
    matchRate: 1.0000,
  },
];

/** Ngày đã cho có ứng sao `sao` hay không. */
export function derivedSaoMatches(sao: DerivedSao, day: DerivedSaoDay): boolean {
  let key: number;
  let value: number;
  switch (sao.kind) {
    case "lunar-month-chi":
      key = day.lunarMonth;
      value = day.dayChi;
      break;
    case "lunar-month-can":
      key = day.lunarMonth;
      value = day.dayCan;
      break;
    case "term-month-chi":
      key = day.termMonthChi;
      value = day.dayChi;
      break;
    case "year-can-day-can":
      key = day.yearCan;
      value = day.dayCan;
      break;
    case "year-can-day-chi":
      key = day.yearCan;
      value = day.dayChi;
      break;
    case "lunar-day":
      key = 0;
      value = day.lunarDay;
      break;
    case "day-cycle":
      key = 0;
      value = day.jd % (sao.period ?? 1);
      break;
  }
  return sao.table[key]?.includes(value) ?? false;
}
